**NumPy Vs List**

In [1]:
import numpy as np

In [2]:
lst1 = ['10','20','30','40']

In [3]:
type(lst1)

list

In [5]:
array = np.array(lst1)
type(array)

numpy.ndarray

** Number of DIM**

In [6]:
array.ndim

1

**List can be collection of different datatype element**

In [7]:
lst2 = ['1',2,'hello world']

In [8]:
lst2

['1', 2, 'hello world']

In [10]:
array2 = np.array(lst2)
array2

array(['1', '2', 'hello world'], dtype='<U21')

In [11]:
print(array2)

['1' '2' 'hello world']


In [12]:

array1 = np.array([[1,2],[4,5]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Array : ", array)
print("Array1 : ", array1)
print("Array2 : ", array2)


print("Dim of array : ", array.ndim)
print("Dim of array1 : ", array1.ndim)
print("Dim of array2 : ", array2.ndim)

print("Shape of array : ", array.shape)              # Howmany rows and columns ?
print("Shape of array1 : ", array1.shape)
print("Shape of array2 : ", array2.shape)


print("Size of array : ", array.size)              # Howmany elements in the array ?
print("Size of array1 : ", array1.size)
print("Size of array2 : ", array2.size)


print("Datatype of array : ", array.dtype)              # What is the datatype of an array ?
print("Datatype of array1 : ", array1.dtype)
print("Datatype of array2 : ", array2.dtype)

array0 = np.zeros((3,3))
print("Zero Array : ", array0)

array1 = np.ones((3,3))
print("Zero Array : ", array1)

Array :  ['10' '20' '30' '40']
Array1 :  [[1 2]
 [4 5]]
Array2 :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dim of array :  1
Dim of array1 :  2
Dim of array2 :  2
Shape of array :  (4,)
Shape of array1 :  (2, 2)
Shape of array2 :  (3, 3)
Size of array :  4
Size of array1 :  4
Size of array2 :  9
Datatype of array :  <U2
Datatype of array1 :  int64
Datatype of array2 :  int64
Zero Array :  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Array :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
